- name: update apt package cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: get epel-repo rpm RHEL6
  get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_version|int == 6

- name: get epel-repo rpm RHEL5
  get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_version|int == 5

- name: install epel-repo rpm
  yum: pkg=/tmp/epel-release.rpm state=installed
  when: ansible_os_family == 'RedHat'

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
  when: ansible_os_family == "Debian"

# @development is a groupinstall, see https://coderwall.com/p/k6goya
- name: install common packages redhat/centos
  yum: pkg={{ item }} state=latest
  with_items:
    - '@development'
    - git
  when: ansible_os_family == "RedHat"

